# Generated by Django 5.1.7 on 2025-04-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_feedback_rating_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='zip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
